export default {
  language: 'language',
  clientDetails: 'client details',
  clientCompanyDetails: 'client company details',
  clientSignatoryDetails: 'client signatory details',
  clientName: 'client name',
  companyName: 'company name',
  quickSearch: 'quick search',
  languageEnglish: 'english',
  languageHungarian: 'hungarian',
  user: 'user',
  settings: 'settings',
  logout: 'logout',
  dashboard: 'dashboard',
  companies: 'companies',
  clients: 'clients',
  addNew: 'add new',
  contracts: 'contracts',
  mails: 'mails',
  inspections: 'inspections',
  invoices: 'invoices',
  services: 'services',
  contactDetails: 'contact details',
  paymentDetails: 'payment details',
  status: 'status',
  contractExpiryTill: 'contract expiry till'
}