export default {
  'add new': 'új hozzáadása',
  'client company details': 'ügyfél céges adatok',
  'client name': 'ügyfél neve',
  'client details': 'ügyfél részletes',
  'clients': 'ügyfelek',
  'companies': 'cégek',
  'company name': 'cég neve',
  'contract expiry till': 'szerződés lejárta',
  'contracts': 'szerződések',
  'dashboard': 'nyitóoldal',
  'english': 'angol',
  'hungarian': 'magyar',
  'inspections': 'ellenőrzések',
  'invoices': 'számlák',
  'language': 'nyelv',
  'logout': 'kijelentkezés',
  'mails': 'levelek',
  'next': 'következő',
  'previous': 'előző',
  'rows per page': 'sor per oldal',
  'quick search': 'gyors keresés',
  'search': 'keresés',
  'settings': 'beállítások',
  'status': 'státusz',
  'user': 'felhasznaló'
}