exports.seed = async knex => {
    const dbName = 'address_countries';

    await knex(dbName).insert([{
        "id": 1,
        "short_name": "US",
        "long_name": "United States"
    }, {
        "id": 2,
        "short_name": "CA",
        "long_name": "Canada"
    }, {
        "id": 3,
        "short_name": "AF",
        "long_name": "Afghanistan"
    }, {
        "id": 4,
        "short_name": "AL",
        "long_name": "Albania"
    }, {
        "id": 5,
        "short_name": "DZ",
        "long_name": "Algeria"
    }, {
        "id": 6,
        "short_name": "AS",
        "long_name": "American Samoa"
    }, {
        "id": 7,
        "short_name": "AD",
        "long_name": "Andorra"
    }, {
        "id": 8,
        "short_name": "AO",
        "long_name": "Angola"
    }, {
        "id": 9,
        "short_name": "AI",
        "long_name": "Anguilla"
    }, {
        "id": 10,
        "short_name": "AQ",
        "long_name": "Antarctica"
    }, {
        "id": 11,
        "short_name": "AG",
        "long_name": "Antigua and/or Barbuda"
    }, {
        "id": 12,
        "short_name": "AR",
        "long_name": "Argentina"
    }, {
        "id": 13,
        "short_name": "AM",
        "long_name": "Armenia"
    }, {
        "id": 14,
        "short_name": "AW",
        "long_name": "Aruba"
    }, {
        "id": 15,
        "short_name": "AU",
        "long_name": "Australia"
    }, {
        "id": 16,
        "short_name": "AT",
        "long_name": "Austria"
    }, {
        "id": 17,
        "short_name": "AZ",
        "long_name": "Azerbaijan"
    }, {
        "id": 18,
        "short_name": "BS",
        "long_name": "Bahamas"
    }, {
        "id": 19,
        "short_name": "BH",
        "long_name": "Bahrain"
    }, {
        "id": 20,
        "short_name": "BD",
        "long_name": "Bangladesh"
    }, {
        "id": 21,
        "short_name": "BB",
        "long_name": "Barbados"
    }, {
        "id": 22,
        "short_name": "BY",
        "long_name": "Belarus"
    }, {
        "id": 23,
        "short_name": "BE",
        "long_name": "Belgium"
    }, {
        "id": 24,
        "short_name": "BZ",
        "long_name": "Belize"
    }, {
        "id": 25,
        "short_name": "BJ",
        "long_name": "Benin"
    }, {
        "id": 26,
        "short_name": "BM",
        "long_name": "Bermuda"
    }, {
        "id": 27,
        "short_name": "BT",
        "long_name": "Bhutan"
    }, {
        "id": 28,
        "short_name": "BO",
        "long_name": "Bolivia"
    }, {
        "id": 29,
        "short_name": "BA",
        "long_name": "Bosnia and Herzegovina"
    }, {
        "id": 30,
        "short_name": "BW",
        "long_name": "Botswana"
    }, {
        "id": 31,
        "short_name": "BV",
        "long_name": "Bouvet Island"
    }, {
        "id": 32,
        "short_name": "BR",
        "long_name": "Brazil"
    }, {
        "id": 33,
        "short_name": "IO",
        "long_name": "British lndian Ocean Territory"
    }, {
        "id": 34,
        "short_name": "BN",
        "long_name": "Brunei Darussalam"
    }, {
        "id": 35,
        "short_name": "BG",
        "long_name": "Bulgaria"
    }, {
        "id": 36,
        "short_name": "BF",
        "long_name": "Burkina Faso"
    }, {
        "id": 37,
        "short_name": "BI",
        "long_name": "Burundi"
    }, {
        "id": 38,
        "short_name": "KH",
        "long_name": "Cambodia"
    }, {
        "id": 39,
        "short_name": "CM",
        "long_name": "Cameroon"
    }, {
        "id": 40,
        "short_name": "CV",
        "long_name": "Cape Verde"
    }, {
        "id": 41,
        "short_name": "KY",
        "long_name": "Cayman Islands"
    }, {
        "id": 42,
        "short_name": "CF",
        "long_name": "Central African Republic"
    }, {
        "id": 43,
        "short_name": "TD",
        "long_name": "Chad"
    }, {
        "id": 44,
        "short_name": "CL",
        "long_name": "Chile"
    }, {
        "id": 45,
        "short_name": "CN",
        "long_name": "China"
    }, {
        "id": 46,
        "short_name": "CX",
        "long_name": "Christmas Island"
    }, {
        "id": 47,
        "short_name": "CC",
        "long_name": "Cocos (Keeling) Islands"
    }, {
        "id": 48,
        "short_name": "CO",
        "long_name": "Colombia"
    }, {
        "id": 49,
        "short_name": "KM",
        "long_name": "Comoros"
    }, {
        "id": 50,
        "short_name": "CG",
        "long_name": "Congo"
    }, {
        "id": 51,
        "short_name": "CK",
        "long_name": "Cook Islands"
    }, {
        "id": 52,
        "short_name": "CR",
        "long_name": "Costa Rica"
    }, {
        "id": 53,
        "short_name": "HR",
        "long_name": "Croatia (Hrvatska)"
    }, {
        "id": 54,
        "short_name": "CU",
        "long_name": "Cuba"
    }, {
        "id": 55,
        "short_name": "CY",
        "long_name": "Cyprus"
    }, {
        "id": 56,
        "short_name": "CZ",
        "long_name": "Czech Republic"
    }, {
        "id": 57,
        "short_name": "CD",
        "long_name": "Democratic Republic of Congo"
    }, {
        "id": 58,
        "short_name": "DK",
        "long_name": "Denmark"
    }, {
        "id": 59,
        "short_name": "DJ",
        "long_name": "Djibouti"
    }, {
        "id": 60,
        "short_name": "DM",
        "long_name": "Dominica"
    }, {
        "id": 61,
        "short_name": "DO",
        "long_name": "Dominican Republic"
    }, {
        "id": 62,
        "short_name": "TP",
        "long_name": "East Timor"
    }, {
        "id": 63,
        "short_name": "EC",
        "long_name": "Ecudaor"
    }, {
        "id": 64,
        "short_name": "EG",
        "long_name": "Egypt"
    }, {
        "id": 65,
        "short_name": "SV",
        "long_name": "El Salvador"
    }, {
        "id": 66,
        "short_name": "GQ",
        "long_name": "Equatorial Guinea"
    }, {
        "id": 67,
        "short_name": "ER",
        "long_name": "Eritrea"
    }, {
        "id": 68,
        "short_name": "EE",
        "long_name": "Estonia"
    }, {
        "id": 69,
        "short_name": "ET",
        "long_name": "Ethiopia"
    }, {
        "id": 70,
        "short_name": "FK",
        "long_name": "Falkland Islands (Malvinas)"
    }, {
        "id": 71,
        "short_name": "FO",
        "long_name": "Faroe Islands"
    }, {
        "id": 72,
        "short_name": "FJ",
        "long_name": "Fiji"
    }, {
        "id": 73,
        "short_name": "FI",
        "long_name": "Finland"
    }, {
        "id": 74,
        "short_name": "FR",
        "long_name": "France"
    }, {
        "id": 75,
        "short_name": "FX",
        "long_name": "France, Metropolitan"
    }, {
        "id": 76,
        "short_name": "GF",
        "long_name": "French Guiana"
    }, {
        "id": 77,
        "short_name": "PF",
        "long_name": "French Polynesia"
    }, {
        "id": 78,
        "short_name": "TF",
        "long_name": "French Southern Territories"
    }, {
        "id": 79,
        "short_name": "GA",
        "long_name": "Gabon"
    }, {
        "id": 80,
        "short_name": "GM",
        "long_name": "Gambia"
    }, {
        "id": 81,
        "short_name": "GE",
        "long_name": "Georgia"
    }, {
        "id": 82,
        "short_name": "DE",
        "long_name": "Germany"
    }, {
        "id": 83,
        "short_name": "GH",
        "long_name": "Ghana"
    }, {
        "id": 84,
        "short_name": "GI",
        "long_name": "Gibraltar"
    }, {
        "id": 85,
        "short_name": "GR",
        "long_name": "Greece"
    }, {
        "id": 86,
        "short_name": "GL",
        "long_name": "Greenland"
    }, {
        "id": 87,
        "short_name": "GD",
        "long_name": "Grenada"
    }, {
        "id": 88,
        "short_name": "GP",
        "long_name": "Guadeloupe"
    }, {
        "id": 89,
        "short_name": "GU",
        "long_name": "Guam"
    }, {
        "id": 90,
        "short_name": "GT",
        "long_name": "Guatemala"
    }, {
        "id": 91,
        "short_name": "GN",
        "long_name": "Guinea"
    }, {
        "id": 92,
        "short_name": "GW",
        "long_name": "Guinea-Bissau"
    }, {
        "id": 93,
        "short_name": "GY",
        "long_name": "Guyana"
    }, {
        "id": 94,
        "short_name": "HT",
        "long_name": "Haiti"
    }, {
        "id": 95,
        "short_name": "HM",
        "long_name": "Heard and Mc Donald Islands"
    }, {
        "id": 96,
        "short_name": "HN",
        "long_name": "Honduras"
    }, {
        "id": 97,
        "short_name": "HK",
        "long_name": "Hong Kong"
    }, {
        "id": 98,
        "short_name": "HU",
        "long_name": "Hungary"
    }, {
        "id": 99,
        "short_name": "IS",
        "long_name": "Iceland"
    }, {
        "id": 100,
        "short_name": "IN",
        "long_name": "India"
    }, {
        "id": 101,
        "short_name": "ID",
        "long_name": "Indonesia"
    }, {
        "id": 102,
        "short_name": "IR",
        "long_name": "Iran (Islamic Republic of)"
    }, {
        "id": 103,
        "short_name": "IQ",
        "long_name": "Iraq"
    }, {
        "id": 104,
        "short_name": "IE",
        "long_name": "Ireland"
    }, {
        "id": 105,
        "short_name": "IL",
        "long_name": "Israel"
    }, {
        "id": 106,
        "short_name": "IT",
        "long_name": "Italy"
    }, {
        "id": 107,
        "short_name": "CI",
        "long_name": "Ivory Coast"
    }, {
        "id": 108,
        "short_name": "JM",
        "long_name": "Jamaica"
    }, {
        "id": 109,
        "short_name": "JP",
        "long_name": "Japan"
    }, {
        "id": 110,
        "short_name": "JO",
        "long_name": "Jordan"
    }, {
        "id": 111,
        "short_name": "KZ",
        "long_name": "Kazakhstan"
    }, {
        "id": 112,
        "short_name": "KE",
        "long_name": "Kenya"
    }, {
        "id": 113,
        "short_name": "KI",
        "long_name": "Kiribati"
    }, {
        "id": 114,
        "short_name": "KP",
        "long_name": "Korea, Democratic People\\'s Republic of"
    }, {
        "id": 115,
        "short_name": "KR",
        "long_name": "Korea, Republic of"
    }, {
        "id": 116,
        "short_name": "KW",
        "long_name": "Kuwait"
    }, {
        "id": 117,
        "short_name": "KG",
        "long_name": "Kyrgyzstan"
    }, {
        "id": 118,
        "short_name": "LA",
        "long_name": "Lao People\\'s Democratic Republic"
    }, {
        "id": 119,
        "short_name": "LV",
        "long_name": "Latvia"
    }, {
        "id": 120,
        "short_name": "LB",
        "long_name": "Lebanon"
    }, {
        "id": 121,
        "short_name": "LS",
        "long_name": "Lesotho"
    }, {
        "id": 122,
        "short_name": "LR",
        "long_name": "Liberia"
    }, {
        "id": 123,
        "short_name": "LY",
        "long_name": "Libyan Arab Jamahiriya"
    }, {
        "id": 124,
        "short_name": "LI",
        "long_name": "Liechtenstein"
    }, {
        "id": 125,
        "short_name": "LT",
        "long_name": "Lithuania"
    }, {
        "id": 126,
        "short_name": "LU",
        "long_name": "Luxembourg"
    }, {
        "id": 127,
        "short_name": "MO",
        "long_name": "Macau"
    }, {
        "id": 128,
        "short_name": "MK",
        "long_name": "Macedonia"
    }, {
        "id": 129,
        "short_name": "MG",
        "long_name": "Madagascar"
    }, {
        "id": 130,
        "short_name": "MW",
        "long_name": "Malawi"
    }, {
        "id": 131,
        "short_name": "MY",
        "long_name": "Malaysia"
    }, {
        "id": 132,
        "short_name": "MV",
        "long_name": "Maldives"
    }, {
        "id": 133,
        "short_name": "ML",
        "long_name": "Mali"
    }, {
        "id": 134,
        "short_name": "MT",
        "long_name": "Malta"
    }, {
        "id": 135,
        "short_name": "MH",
        "long_name": "Marshall Islands"
    }, {
        "id": 136,
        "short_name": "MQ",
        "long_name": "Martinique"
    }, {
        "id": 137,
        "short_name": "MR",
        "long_name": "Mauritania"
    }, {
        "id": 138,
        "short_name": "MU",
        "long_name": "Mauritius"
    }, {
        "id": 139,
        "short_name": "TY",
        "long_name": "Mayotte"
    }, {
        "id": 140,
        "short_name": "MX",
        "long_name": "Mexico"
    }, {
        "id": 141,
        "short_name": "FM",
        "long_name": "Micronesia, Federated States of"
    }, {
        "id": 142,
        "short_name": "MD",
        "long_name": "Moldova, Republic of"
    }, {
        "id": 143,
        "short_name": "MC",
        "long_name": "Monaco"
    }, {
        "id": 144,
        "short_name": "MN",
        "long_name": "Mongolia"
    }, {
        "id": 145,
        "short_name": "MS",
        "long_name": "Montserrat"
    }, {
        "id": 146,
        "short_name": "MA",
        "long_name": "Morocco"
    }, {
        "id": 147,
        "short_name": "MZ",
        "long_name": "Mozambique"
    }, {
        "id": 148,
        "short_name": "MM",
        "long_name": "Myanmar"
    }, {
        "id": 149,
        "short_name": "NA",
        "long_name": "Namibia"
    }, {
        "id": 150,
        "short_name": "NR",
        "long_name": "Nauru"
    }, {
        "id": 151,
        "short_name": "NP",
        "long_name": "Nepal"
    }, {
        "id": 152,
        "short_name": "NL",
        "long_name": "Netherlands"
    }, {
        "id": 153,
        "short_name": "AN",
        "long_name": "Netherlands Antilles"
    }, {
        "id": 154,
        "short_name": "NC",
        "long_name": "New Caledonia"
    }, {
        "id": 155,
        "short_name": "NZ",
        "long_name": "New Zealand"
    }, {
        "id": 156,
        "short_name": "NI",
        "long_name": "Nicaragua"
    }, {
        "id": 157,
        "short_name": "NE",
        "long_name": "Niger"
    }, {
        "id": 158,
        "short_name": "NG",
        "long_name": "Nigeria"
    }, {
        "id": 159,
        "short_name": "NU",
        "long_name": "Niue"
    }, {
        "id": 160,
        "short_name": "NF",
        "long_name": "Norfork Island"
    }, {
        "id": 161,
        "short_name": "MP",
        "long_name": "Northern Mariana Islands"
    }, {
        "id": 162,
        "short_name": "NO",
        "long_name": "Norway"
    }, {
        "id": 163,
        "short_name": "OM",
        "long_name": "Oman"
    }, {
        "id": 164,
        "short_name": "PK",
        "long_name": "Pakistan"
    }, {
        "id": 165,
        "short_name": "PW",
        "long_name": "Palau"
    }, {
        "id": 166,
        "short_name": "PA",
        "long_name": "Panama"
    }, {
        "id": 167,
        "short_name": "PG",
        "long_name": "Papua New Guinea"
    }, {
        "id": 168,
        "short_name": "PY",
        "long_name": "Paraguay"
    }, {
        "id": 169,
        "short_name": "PE",
        "long_name": "Peru"
    }, {
        "id": 170,
        "short_name": "PH",
        "long_name": "Philippines"
    }, {
        "id": 171,
        "short_name": "PN",
        "long_name": "Pitcairn"
    }, {
        "id": 172,
        "short_name": "PL",
        "long_name": "Poland"
    }, {
        "id": 173,
        "short_name": "PT",
        "long_name": "Portugal"
    }, {
        "id": 174,
        "short_name": "PR",
        "long_name": "Puerto Rico"
    }, {
        "id": 175,
        "short_name": "QA",
        "long_name": "Qatar"
    }, {
        "id": 176,
        "short_name": "SS",
        "long_name": "Republic of South Sudan"
    }, {
        "id": 177,
        "short_name": "RE",
        "long_name": "Reunion"
    }, {
        "id": 178,
        "short_name": "RO",
        "long_name": "Romania"
    }, {
        "id": 179,
        "short_name": "RU",
        "long_name": "Russian Federation"
    }, {
        "id": 180,
        "short_name": "RW",
        "long_name": "Rwanda"
    }, {
        "id": 181,
        "short_name": "KN",
        "long_name": "Saint Kitts and Nevis"
    }, {
        "id": 182,
        "short_name": "LC",
        "long_name": "Saint Lucia"
    }, {
        "id": 183,
        "short_name": "VC",
        "long_name": "Saint Vincent and the Grenadines"
    }, {
        "id": 184,
        "short_name": "WS",
        "long_name": "Samoa"
    }, {
        "id": 185,
        "short_name": "SM",
        "long_name": "San Marino"
    }, {
        "id": 186,
        "short_name": "ST",
        "long_name": "Sao Tome and Principe"
    }, {
        "id": 187,
        "short_name": "SA",
        "long_name": "Saudi Arabia"
    }, {
        "id": 188,
        "short_name": "SN",
        "long_name": "Senegal"
    }, {
        "id": 189,
        "short_name": "RS",
        "long_name": "Serbia"
    }, {
        "id": 190,
        "short_name": "SC",
        "long_name": "Seychelles"
    }, {
        "id": 191,
        "short_name": "SL",
        "long_name": "Sierra Leone"
    }, {
        "id": 192,
        "short_name": "SG",
        "long_name": "Singapore"
    }, {
        "id": 193,
        "short_name": "SK",
        "long_name": "Slovakia"
    }, {
        "id": 194,
        "short_name": "SI",
        "long_name": "Slovenia"
    }, {
        "id": 195,
        "short_name": "SB",
        "long_name": "Solomon Islands"
    }, {
        "id": 196,
        "short_name": "SO",
        "long_name": "Somalia"
    }, {
        "id": 197,
        "short_name": "ZA",
        "long_name": "South Africa"
    }, {
        "id": 198,
        "short_name": "GS",
        "long_name": "South Georgia South Sandwich Islands"
    }, {
        "id": 199,
        "short_name": "ES",
        "long_name": "Spain"
    }, {
        "id": 200,
        "short_name": "LK",
        "long_name": "Sri Lanka"
    }, {
        "id": 201,
        "short_name": "SH",
        "long_name": "St. Helena"
    }, {
        "id": 202,
        "short_name": "PM",
        "long_name": "St. Pierre and Miquelon"
    }, {
        "id": 203,
        "short_name": "SD",
        "long_name": "Sudan"
    }, {
        "id": 204,
        "short_name": "SR",
        "long_name": "Suriname"
    }, {
        "id": 205,
        "short_name": "SJ",
        "long_name": "Svalbarn and Jan Mayen Islands"
    }, {
        "id": 206,
        "short_name": "SZ",
        "long_name": "Swaziland"
    }, {
        "id": 207,
        "short_name": "SE",
        "long_name": "Sweden"
    }, {
        "id": 208,
        "short_name": "CH",
        "long_name": "Switzerland"
    }, {
        "id": 209,
        "short_name": "SY",
        "long_name": "Syrian Arab Republic"
    }, {
        "id": 210,
        "short_name": "TW",
        "long_name": "Taiwan"
    }, {
        "id": 211,
        "short_name": "TJ",
        "long_name": "Tajikistan"
    }, {
        "id": 212,
        "short_name": "TZ",
        "long_name": "Tanzania, United Republic of"
    }, {
        "id": 213,
        "short_name": "TH",
        "long_name": "Thailand"
    }, {
        "id": 214,
        "short_name": "TG",
        "long_name": "Togo"
    }, {
        "id": 215,
        "short_name": "TK",
        "long_name": "Tokelau"
    }, {
        "id": 216,
        "short_name": "TO",
        "long_name": "Tonga"
    }, {
        "id": 217,
        "short_name": "TT",
        "long_name": "Trinidad and Tobago"
    }, {
        "id": 218,
        "short_name": "TN",
        "long_name": "Tunisia"
    }, {
        "id": 219,
        "short_name": "TR",
        "long_name": "Turkey"
    }, {
        "id": 220,
        "short_name": "TM",
        "long_name": "Turkmenistan"
    }, {
        "id": 221,
        "short_name": "TC",
        "long_name": "Turks and Caicos Islands"
    }, {
        "id": 222,
        "short_name": "TV",
        "long_name": "Tuvalu"
    }, {
        "id": 223,
        "short_name": "UG",
        "long_name": "Uganda"
    }, {
        "id": 224,
        "short_name": "UA",
        "long_name": "Ukraine"
    }, {
        "id": 225,
        "short_name": "AE",
        "long_name": "United Arab Emirates"
    }, {
        "id": 226,
        "short_name": "GB",
        "long_name": "United Kingdom"
    }, {
        "id": 227,
        "short_name": "UM",
        "long_name": "United States minor outlying islands"
    }, {
        "id": 228,
        "short_name": "UY",
        "long_name": "Uruguay"
    }, {
        "id": 229,
        "short_name": "UZ",
        "long_name": "Uzbekistan"
    }, {
        "id": 230,
        "short_name": "VU",
        "long_name": "Vanuatu"
    }, {
        "id": 231,
        "short_name": "VA",
        "long_name": "Vatican City State"
    }, {
        "id": 232,
        "short_name": "VE",
        "long_name": "Venezuela"
    }, {
        "id": 233,
        "short_name": "VN",
        "long_name": "Vietnam"
    }, {
        "id": 234,
        "short_name": "VG",
        "long_name": "Virgin Islands (British)"
    }, {
        "id": 235,
        "short_name": "VI",
        "long_name": "Virgin Islands (U.S.)"
    }, {
        "id": 236,
        "short_name": "WF",
        "long_name": "Wallis and Futuna Islands"
    }, {
        "id": 237,
        "short_name": "EH",
        "long_name": "Western Sahara"
    }, {
        "id": 238,
        "short_name": "YE",
        "long_name": "Yemen"
    }, {
        "id": 239,
        "short_name": "YU",
        "long_name": "Yugoslavia"
    }, {
        "id": 240,
        "short_name": "ZR",
        "long_name": "Zaire"
    }, {
        "id": 241,
        "short_name": "ZM",
        "long_name": "Zambia"
    }, {
        "id": 242,
        "short_name": "ZW",
        "long_name": "Zimbabwe"
    }]);

    await knex.raw(`select setval(\'${dbName}_id_seq\', max(id)) from ${dbName}`);
};