exports.seed = async knex => {
    await knex('address_countries').del();
    await knex('address_countries').insert([{
        "id": 0,
        "long_name": "Afghanistan",
        "short_name": "AF"
    }, {
        "id": 1,
        "long_name": "Åland Islands",
        "short_name": "AX"
    }, {
        "id": 2,
        "long_name": "Albania",
        "short_name": "AL"
    }, {
        "id": 3,
        "long_name": "Algeria",
        "short_name": "DZ"
    }, {
        "id": 4,
        "long_name": "American Samoa",
        "short_name": "AS"
    }, {
        "id": 5,
        "long_name": "Andorra",
        "short_name": "AD"
    }, {
        "id": 6,
        "long_name": "Angola",
        "short_name": "AO"
    }, {
        "id": 7,
        "long_name": "Anguilla",
        "short_name": "AI"
    }, {
        "id": 8,
        "long_name": "Antarctica",
        "short_name": "AQ"
    }, {
        "id": 9,
        "long_name": "Antigua and Barbuda",
        "short_name": "AG"
    }, {
        "id": 10,
        "long_name": "Argentina",
        "short_name": "AR"
    }, {
        "id": 11,
        "long_name": "Armenia",
        "short_name": "AM"
    }, {
        "id": 12,
        "long_name": "Aruba",
        "short_name": "AW"
    }, {
        "id": 13,
        "long_name": "Australia",
        "short_name": "AU"
    }, {
        "id": 14,
        "long_name": "Austria",
        "short_name": "AT"
    }, {
        "id": 15,
        "long_name": "Azerbaijan",
        "short_name": "AZ"
    }, {
        "id": 16,
        "long_name": "Bahamas (the)",
        "short_name": "BS"
    }, {
        "id": 17,
        "long_name": "Bahrain",
        "short_name": "BH"
    }, {
        "id": 18,
        "long_name": "Bangladesh",
        "short_name": "BD"
    }, {
        "id": 19,
        "long_name": "Barbados",
        "short_name": "BB"
    }, {
        "id": 20,
        "long_name": "Belarus",
        "short_name": "BY"
    }, {
        "id": 21,
        "long_name": "Belgium",
        "short_name": "BE"
    }, {
        "id": 22,
        "long_name": "Belize",
        "short_name": "BZ"
    }, {
        "id": 23,
        "long_name": "Benin",
        "short_name": "BJ"
    }, {
        "id": 24,
        "long_name": "Bermuda",
        "short_name": "BM"
    }, {
        "id": 25,
        "long_name": "Bhutan",
        "short_name": "BT"
    }, {
        "id": 26,
        "long_name": "Bolivia (Plurinational State of)",
        "short_name": "BO"
    }, {
        "id": 27,
        "long_name": "Bonaire, Sint Eustatius and Saba",
        "short_name": "BQ"
    }, {
        "id": 28,
        "long_name": "Bosnia and Herzegovina",
        "short_name": "BA"
    }, {
        "id": 29,
        "long_name": "Botswana",
        "short_name": "BW"
    }, {
        "id": 30,
        "long_name": "Bouvet Island",
        "short_name": "BV"
    }, {
        "id": 31,
        "long_name": "Brazil",
        "short_name": "BR"
    }, {
        "id": 32,
        "long_name": "British Indian Ocean Territory (the)",
        "short_name": "IO"
    }, {
        "id": 33,
        "long_name": "Brunei Darussalam",
        "short_name": "BN"
    }, {
        "id": 34,
        "long_name": "Bulgaria",
        "short_name": "BG"
    }, {
        "id": 35,
        "long_name": "Burkina Faso",
        "short_name": "BF"
    }, {
        "id": 36,
        "long_name": "Burundi",
        "short_name": "BI"
    }, {
        "id": 37,
        "long_name": "Cabo Verde",
        "short_name": "CV"
    }, {
        "id": 38,
        "long_name": "Cambodia",
        "short_name": "KH"
    }, {
        "id": 39,
        "long_name": "Cameroon",
        "short_name": "CM"
    }, {
        "id": 40,
        "long_name": "Canada",
        "short_name": "CA"
    }, {
        "id": 41,
        "long_name": "Cayman Islands (the)",
        "short_name": "KY"
    }, {
        "id": 42,
        "long_name": "Central African Republic (the)",
        "short_name": "CF"
    }, {
        "id": 43,
        "long_name": "Chad",
        "short_name": "TD"
    }, {
        "id": 44,
        "long_name": "Chile",
        "short_name": "CL"
    }, {
        "id": 45,
        "long_name": "China",
        "short_name": "CN"
    }, {
        "id": 46,
        "long_name": "Christmas Island",
        "short_name": "CX"
    }, {
        "id": 47,
        "long_name": "Cocos (Keeling) Islands (the)",
        "short_name": "CC"
    }, {
        "id": 48,
        "long_name": "Colombia",
        "short_name": "CO"
    }, {
        "id": 49,
        "long_name": "Comoros (the)",
        "short_name": "KM"
    }, {
        "id": 50,
        "long_name": "Congo (the Democratic Republic of the)",
        "short_name": "CD"
    }, {
        "id": 51,
        "long_name": "Congo (the)",
        "short_name": "CG"
    }, {
        "id": 52,
        "long_name": "Cook Islands (the)",
        "short_name": "CK"
    }, {
        "id": 53,
        "long_name": "Costa Rica",
        "short_name": "CR"
    }, {
        "id": 54,
        "long_name": "Côte d'Ivoire",
        "short_name": "CI"
    }, {
        "id": 55,
        "long_name": "Croatia",
        "short_name": "HR"
    }, {
        "id": 56,
        "long_name": "Cuba",
        "short_name": "CU"
    }, {
        "id": 57,
        "long_name": "Curaçao",
        "short_name": "CW"
    }, {
        "id": 58,
        "long_name": "Cyprus",
        "short_name": "CY"
    }, {
        "id": 59,
        "long_name": "Czech Republic (the)",
        "short_name": "CZ"
    }, {
        "id": 60,
        "long_name": "Denmark",
        "short_name": "DK"
    }, {
        "id": 61,
        "long_name": "Djibouti",
        "short_name": "DJ"
    }, {
        "id": 62,
        "long_name": "Dominica",
        "short_name": "DM"
    }, {
        "id": 63,
        "long_name": "Dominican Republic (the)",
        "short_name": "DO"
    }, {
        "id": 64,
        "long_name": "Ecuador",
        "short_name": "EC"
    }, {
        "id": 65,
        "long_name": "Egypt",
        "short_name": "EG"
    }, {
        "id": 66,
        "long_name": "El Salvador",
        "short_name": "SV"
    }, {
        "id": 67,
        "long_name": "Equatorial Guinea",
        "short_name": "GQ"
    }, {
        "id": 68,
        "long_name": "Eritrea",
        "short_name": "ER"
    }, {
        "id": 69,
        "long_name": "Estonia",
        "short_name": "EE"
    }, {
        "id": 70,
        "long_name": "Ethiopia",
        "short_name": "ET"
    }, {
        "id": 71,
        "long_name": "Falkland Islands (the) [Malvinas]",
        "short_name": "FK"
    }, {
        "id": 72,
        "long_name": "Faroe Islands (the)",
        "short_name": "FO"
    }, {
        "id": 73,
        "long_name": "Fiji",
        "short_name": "FJ"
    }, {
        "id": 74,
        "long_name": "Finland",
        "short_name": "FI"
    }, {
        "id": 75,
        "long_name": "France",
        "short_name": "FR"
    }, {
        "id": 76,
        "long_name": "French Guiana",
        "short_name": "GF"
    }, {
        "id": 77,
        "long_name": "French Polynesia",
        "short_name": "PF"
    }, {
        "id": 78,
        "long_name": "French Southern Territories (the)",
        "short_name": "TF"
    }, {
        "id": 79,
        "long_name": "Gabon",
        "short_name": "GA"
    }, {
        "id": 80,
        "long_name": "Gambia (the)",
        "short_name": "GM"
    }, {
        "id": 81,
        "long_name": "Georgia",
        "short_name": "GE"
    }, {
        "id": 82,
        "long_name": "Germany",
        "short_name": "DE"
    }, {
        "id": 83,
        "long_name": "Ghana",
        "short_name": "GH"
    }, {
        "id": 84,
        "long_name": "Gibraltar",
        "short_name": "GI"
    }, {
        "id": 85,
        "long_name": "Greece",
        "short_name": "GR"
    }, {
        "id": 86,
        "long_name": "Greenland",
        "short_name": "GL"
    }, {
        "id": 87,
        "long_name": "Grenada",
        "short_name": "GD"
    }, {
        "id": 88,
        "long_name": "Guadeloupe",
        "short_name": "GP"
    }, {
        "id": 89,
        "long_name": "Guam",
        "short_name": "GU"
    }, {
        "id": 90,
        "long_name": "Guatemala",
        "short_name": "GT"
    }, {
        "id": 91,
        "long_name": "Guernsey",
        "short_name": "GG"
    }, {
        "id": 92,
        "long_name": "Guinea",
        "short_name": "GN"
    }, {
        "id": 93,
        "long_name": "Guinea-Bissau",
        "short_name": "GW"
    }, {
        "id": 94,
        "long_name": "Guyana",
        "short_name": "GY"
    }, {
        "id": 95,
        "long_name": "Haiti",
        "short_name": "HT"
    }, {
        "id": 96,
        "long_name": "Heard Island and McDonald Islands",
        "short_name": "HM"
    }, {
        "id": 97,
        "long_name": "Holy See (the)",
        "short_name": "VA"
    }, {
        "id": 98,
        "long_name": "Honduras",
        "short_name": "HN"
    }, {
        "id": 99,
        "long_name": "Hong Kong",
        "short_name": "HK"
    }, {
        "id": 100,
        "long_name": "Hungary",
        "short_name": "HU"
    }, {
        "id": 101,
        "long_name": "Iceland",
        "short_name": "IS"
    }, {
        "id": 102,
        "long_name": "India",
        "short_name": "IN"
    }, {
        "id": 103,
        "long_name": "Indonesia",
        "short_name": "ID"
    }, {
        "id": 104,
        "long_name": "Iran (Islamic Republic of)",
        "short_name": "IR"
    }, {
        "id": 105,
        "long_name": "Iraq",
        "short_name": "IQ"
    }, {
        "id": 106,
        "long_name": "Ireland",
        "short_name": "IE"
    }, {
        "id": 107,
        "long_name": "Isle of Man",
        "short_name": "IM"
    }, {
        "id": 108,
        "long_name": "Israel",
        "short_name": "IL"
    }, {
        "id": 109,
        "long_name": "Italy",
        "short_name": "IT"
    }, {
        "id": 110,
        "long_name": "Jamaica",
        "short_name": "JM"
    }, {
        "id": 111,
        "long_name": "Japan",
        "short_name": "JP"
    }, {
        "id": 112,
        "long_name": "Jersey",
        "short_name": "JE"
    }, {
        "id": 113,
        "long_name": "Jordan",
        "short_name": "JO"
    }, {
        "id": 114,
        "long_name": "Kazakhstan",
        "short_name": "KZ"
    }, {
        "id": 115,
        "long_name": "Kenya",
        "short_name": "KE"
    }, {
        "id": 116,
        "long_name": "Kiribati",
        "short_name": "KI"
    }, {
        "id": 117,
        "long_name": "Korea (the Democratic People's Republic of)",
        "short_name": "KP"
    }, {
        "id": 118,
        "long_name": "Korea (the Republic of)",
        "short_name": "KR"
    }, {
        "id": 119,
        "long_name": "Kuwait",
        "short_name": "KW"
    }, {
        "id": 120,
        "long_name": "Kyrgyzstan",
        "short_name": "KG"
    }, {
        "id": 121,
        "long_name": "Lao People's Democratic Republic (the)",
        "short_name": "LA"
    }, {
        "id": 122,
        "long_name": "Latvia",
        "short_name": "LV"
    }, {
        "id": 123,
        "long_name": "Lebanon",
        "short_name": "LB"
    }, {
        "id": 124,
        "long_name": "Lesotho",
        "short_name": "LS"
    }, {
        "id": 125,
        "long_name": "Liberia",
        "short_name": "LR"
    }, {
        "id": 126,
        "long_name": "Libya",
        "short_name": "LY"
    }, {
        "id": 127,
        "long_name": "Liechtenstein",
        "short_name": "LI"
    }, {
        "id": 128,
        "long_name": "Lithuania",
        "short_name": "LT"
    }, {
        "id": 129,
        "long_name": "Luxembourg",
        "short_name": "LU"
    }, {
        "id": 130,
        "long_name": "Macao",
        "short_name": "MO"
    }, {
        "id": 131,
        "long_name": "Macedonia (the former Yugoslav Republic of)",
        "short_name": "MK"
    }, {
        "id": 132,
        "long_name": "Madagascar",
        "short_name": "MG"
    }, {
        "id": 133,
        "long_name": "Malawi",
        "short_name": "MW"
    }, {
        "id": 134,
        "long_name": "Malaysia",
        "short_name": "MY"
    }, {
        "id": 135,
        "long_name": "Maldives",
        "short_name": "MV"
    }, {
        "id": 136,
        "long_name": "Mali",
        "short_name": "ML"
    }, {
        "id": 137,
        "long_name": "Malta",
        "short_name": "MT"
    }, {
        "id": 138,
        "long_name": "Marshall Islands (the)",
        "short_name": "MH"
    }, {
        "id": 139,
        "long_name": "Martinique",
        "short_name": "MQ"
    }, {
        "id": 140,
        "long_name": "Mauritania",
        "short_name": "MR"
    }, {
        "id": 141,
        "long_name": "Mauritius",
        "short_name": "MU"
    }, {
        "id": 142,
        "long_name": "Mayotte",
        "short_name": "YT"
    }, {
        "id": 143,
        "long_name": "Mexico",
        "short_name": "MX"
    }, {
        "id": 144,
        "long_name": "Micronesia (Federated States of)",
        "short_name": "FM"
    }, {
        "id": 145,
        "long_name": "Moldova (the Republic of)",
        "short_name": "MD"
    }, {
        "id": 146,
        "long_name": "Monaco",
        "short_name": "MC"
    }, {
        "id": 147,
        "long_name": "Mongolia",
        "short_name": "MN"
    }, {
        "id": 148,
        "long_name": "Montenegro",
        "short_name": "ME"
    }, {
        "id": 149,
        "long_name": "Montserrat",
        "short_name": "MS"
    }, {
        "id": 150,
        "long_name": "Morocco",
        "short_name": "MA"
    }, {
        "id": 151,
        "long_name": "Mozambique",
        "short_name": "MZ"
    }, {
        "id": 152,
        "long_name": "Myanmar",
        "short_name": "MM"
    }, {
        "id": 153,
        "long_name": "Namibia",
        "short_name": "NA"
    }, {
        "id": 154,
        "long_name": "Nauru",
        "short_name": "NR"
    }, {
        "id": 155,
        "long_name": "Nepal",
        "short_name": "NP"
    }, {
        "id": 156,
        "long_name": "Netherlands (the)",
        "short_name": "NL"
    }, {
        "id": 157,
        "long_name": "New Caledonia",
        "short_name": "NC"
    }, {
        "id": 158,
        "long_name": "New Zealand",
        "short_name": "NZ"
    }, {
        "id": 159,
        "long_name": "Nicaragua",
        "short_name": "NI"
    }, {
        "id": 160,
        "long_name": "Niger (the)",
        "short_name": "NE"
    }, {
        "id": 161,
        "long_name": "Nigeria",
        "short_name": "NG"
    }, {
        "id": 162,
        "long_name": "Niue",
        "short_name": "NU"
    }, {
        "id": 163,
        "long_name": "Norfolk Island",
        "short_name": "NF"
    }, {
        "id": 164,
        "long_name": "Northern Mariana Islands (the)",
        "short_name": "MP"
    }, {
        "id": 165,
        "long_name": "Norway",
        "short_name": "NO"
    }, {
        "id": 166,
        "long_name": "Oman",
        "short_name": "OM"
    }, {
        "id": 167,
        "long_name": "Pakistan",
        "short_name": "PK"
    }, {
        "id": 168,
        "long_name": "Palau",
        "short_name": "PW"
    }, {
        "id": 169,
        "long_name": "Palestine, State of",
        "short_name": "PS"
    }, {
        "id": 170,
        "long_name": "Panama",
        "short_name": "PA"
    }, {
        "id": 171,
        "long_name": "Papua New Guinea",
        "short_name": "PG"
    }, {
        "id": 172,
        "long_name": "Paraguay",
        "short_name": "PY"
    }, {
        "id": 173,
        "long_name": "Peru",
        "short_name": "PE"
    }, {
        "id": 174,
        "long_name": "Philippines (the)",
        "short_name": "PH"
    }, {
        "id": 175,
        "long_name": "Pitcairn",
        "short_name": "PN"
    }, {
        "id": 176,
        "long_name": "Poland",
        "short_name": "PL"
    }, {
        "id": 177,
        "long_name": "Portugal",
        "short_name": "PT"
    }, {
        "id": 178,
        "long_name": "Puerto Rico",
        "short_name": "PR"
    }, {
        "id": 179,
        "long_name": "Qatar",
        "short_name": "QA"
    }, {
        "id": 180,
        "long_name": "Réunion",
        "short_name": "RE"
    }, {
        "id": 181,
        "long_name": "Romania",
        "short_name": "RO"
    }, {
        "id": 182,
        "long_name": "Russian Federation (the)",
        "short_name": "RU"
    }, {
        "id": 183,
        "long_name": "Rwanda",
        "short_name": "RW"
    }, {
        "id": 184,
        "long_name": "Saint Barthélemy",
        "short_name": "BL"
    }, {
        "id": 185,
        "long_name": "Saint Helena, Ascension and Tristan da Cunha",
        "short_name": "SH"
    }, {
        "id": 186,
        "long_name": "Saint Kitts and Nevis",
        "short_name": "KN"
    }, {
        "id": 187,
        "long_name": "Saint Lucia",
        "short_name": "LC"
    }, {
        "id": 188,
        "long_name": "Saint Martin (French part)",
        "short_name": "MF"
    }, {
        "id": 189,
        "long_name": "Saint Pierre and Miquelon",
        "short_name": "PM"
    }, {
        "id": 190,
        "long_name": "Saint Vincent and the Grenadines",
        "short_name": "VC"
    }, {
        "id": 191,
        "long_name": "Samoa",
        "short_name": "WS"
    }, {
        "id": 192,
        "long_name": "San Marino",
        "short_name": "SM"
    }, {
        "id": 193,
        "long_name": "Sao Tome and Principe",
        "short_name": "ST"
    }, {
        "id": 194,
        "long_name": "Saudi Arabia",
        "short_name": "SA"
    }, {
        "id": 195,
        "long_name": "Senegal",
        "short_name": "SN"
    }, {
        "id": 196,
        "long_name": "Serbia",
        "short_name": "RS"
    }, {
        "id": 197,
        "long_name": "Seychelles",
        "short_name": "SC"
    }, {
        "id": 198,
        "long_name": "Sierra Leone",
        "short_name": "SL"
    }, {
        "id": 199,
        "long_name": "Singapore",
        "short_name": "SG"
    }, {
        "id": 200,
        "long_name": "Sint Maarten (Dutch part)",
        "short_name": "SX"
    }, {
        "id": 201,
        "long_name": "Slovakia",
        "short_name": "SK"
    }, {
        "id": 202,
        "long_name": "Slovenia",
        "short_name": "SI"
    }, {
        "id": 203,
        "long_name": "Solomon Islands",
        "short_name": "SB"
    }, {
        "id": 204,
        "long_name": "Somalia",
        "short_name": "SO"
    }, {
        "id": 205,
        "long_name": "South Africa",
        "short_name": "ZA"
    }, {
        "id": 206,
        "long_name": "South Georgia and the South Sandwich Islands",
        "short_name": "GS"
    }, {
        "id": 207,
        "long_name": "South Sudan",
        "short_name": "SS"
    }, {
        "id": 208,
        "long_name": "Spain",
        "short_name": "ES"
    }, {
        "id": 209,
        "long_name": "Sri Lanka",
        "short_name": "LK"
    }, {
        "id": 210,
        "long_name": "Sudan (the)",
        "short_name": "SD"
    }, {
        "id": 211,
        "long_name": "Suriname",
        "short_name": "SR"
    }, {
        "id": 212,
        "long_name": "Svalbard and Jan Mayen",
        "short_name": "SJ"
    }, {
        "id": 213,
        "long_name": "Swaziland",
        "short_name": "SZ"
    }, {
        "id": 214,
        "long_name": "Sweden",
        "short_name": "SE"
    }, {
        "id": 215,
        "long_name": "Switzerland",
        "short_name": "CH"
    }, {
        "id": 216,
        "long_name": "Syrian Arab Republic",
        "short_name": "SY"
    }, {
        "id": 217,
        "long_name": "Taiwan (Province of China)",
        "short_name": "TW"
    }, {
        "id": 218,
        "long_name": "Tajikistan",
        "short_name": "TJ"
    }, {
        "id": 219,
        "long_name": "Tanzania, United Republic of",
        "short_name": "TZ"
    }, {
        "id": 220,
        "long_name": "Thailand",
        "short_name": "TH"
    }, {
        "id": 221,
        "long_name": "Timor-Leste",
        "short_name": "TL"
    }, {
        "id": 222,
        "long_name": "Togo",
        "short_name": "TG"
    }, {
        "id": 223,
        "long_name": "Tokelau",
        "short_name": "TK"
    }, {
        "id": 224,
        "long_name": "Tonga",
        "short_name": "TO"
    }, {
        "id": 225,
        "long_name": "Trinidad and Tobago",
        "short_name": "TT"
    }, {
        "id": 226,
        "long_name": "Tunisia",
        "short_name": "TN"
    }, {
        "id": 227,
        "long_name": "Turkey",
        "short_name": "TR"
    }, {
        "id": 228,
        "long_name": "Turkmenistan",
        "short_name": "TM"
    }, {
        "id": 229,
        "long_name": "Turks and Caicos Islands (the)",
        "short_name": "TC"
    }, {
        "id": 230,
        "long_name": "Tuvalu",
        "short_name": "TV"
    }, {
        "id": 231,
        "long_name": "Uganda",
        "short_name": "UG"
    }, {
        "id": 232,
        "long_name": "Ukraine",
        "short_name": "UA"
    }, {
        "id": 233,
        "long_name": "United Arab Emirates (the)",
        "short_name": "AE"
    }, {
        "id": 234,
        "long_name": "United Kingdom of Great Britain and Northern Ireland (the)",
        "short_name": "GB"
    }, {
        "id": 235,
        "long_name": "United States Minor Outlying Islands (the)",
        "short_name": "UM"
    }, {
        "id": 236,
        "long_name": "United States of America (the)",
        "short_name": "US"
    }, {
        "id": 237,
        "long_name": "Uruguay",
        "short_name": "UY"
    }, {
        "id": 238,
        "long_name": "Uzbekistan",
        "short_name": "UZ"
    }, {
        "id": 239,
        "long_name": "Vanuatu",
        "short_name": "VU"
    }, {
        "id": 240,
        "long_name": "Venezuela (Bolivarian Republic of)",
        "short_name": "VE"
    }, {
        "id": 241,
        "long_name": "Viet Nam",
        "short_name": "VN"
    }, {
        "id": 242,
        "long_name": "Virgin Islands (British)",
        "short_name": "VG"
    }, {
        "id": 243,
        "long_name": "Virgin Islands (U.S.)",
        "short_name": "VI"
    }, {
        "id": 244,
        "long_name": "Wallis and Futuna",
        "short_name": "WF"
    }, {
        "id": 245,
        "long_name": "Western Sahara*",
        "short_name": "EH"
    }, {
        "id": 246,
        "long_name": "Yemen",
        "short_name": "YE"
    }, {
        "id": 247,
        "long_name": "Zambia",
        "short_name": "ZM"
    }, {
        "id": 248,
        "long_name": "Zimbabwe",
        "short_name": "ZW"
    }]);
};